# Generated by Django 2.1 on 2019-08-09 18:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('time', models.DateTimeField(verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=50, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Price')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Event')),
            ],
        ),
    ]
