# Generated by Django 2.1 on 2019-08-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='event',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='tickets.Event'),
        ),
    ]
