# Generated by Django 2.1 on 2019-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190809_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(to='tickets.Tickets'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='event_number',
            field=models.ManyToManyField(related_name='gigs', to='tickets.Event'),
        ),
    ]
