# Generated by Django 2.1 on 2019-08-11 14:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190809_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPruchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('status', models.CharField(default='booked', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=50, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='event_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='tickets.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='tickets.TicketType'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_type',
            field=models.ManyToManyField(to='tickets.TicketType'),
        ),
    ]
