# Generated by Django 2.1 on 2019-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_event_tickets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpruchase',
            name='operation',
            field=models.CharField(choices=[('R', 'reserve'), ('P', 'purchase')], default='reserve', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketpruchase',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
