# Generated by Django 2.1 on 2019-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190811_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('ticket', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.TimeField(blank=True)),
                ('ticket', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketPruchase',
        ),
    ]
