# Generated by Django 2.1 on 2019-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190811_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
