# Generated by Django 2.1 on 2019-08-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190812_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketpurchase',
            old_name='amount',
            new_name='quantity',
        ),
    ]
