# Generated by Django 2.1 on 2019-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190812_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
